name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_lambda:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        env:
          CI: true
        run: npm ci
